language: php

php:
  - 7.1

before_script:
  - echo 'memory_limit = 256M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/apigen generate vendor/greenter --destination docs
 
after_success:
  - chmod +x ./bin/deploy.sh
  - ./bin/deploy.sh
